spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: h2
    password: h2
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher